### ISSUE TITLE
No graph writer for null

### ISSUE THREAD

**Issue by renespeck** [dice-group/FOX#46]
`
18/Apr/201814:45:02  INFO [Thread-309] (FoxWebLog.java:setMessage:44) - Running Fox done.
18/Apr/201814:45:02  INFO [Thread-309] (AFox.java:infoLog:54) - Running Fox done.
18/Apr/201814:45:02 ERROR [qtp478039926-17] (FoxServer.java:lambda$mapRoutes$2:255) - No graph writer for null
org.apache.jena.riot.RiotException: No graph writer for null
        at org.apache.jena.riot.RDFDataMgr.createGraphWriter$(RDFDataMgr.java:1199)
        at org.apache.jena.riot.RDFDataMgr.write$(RDFDataMgr.java:1216)
        at org.apache.jena.riot.RDFDataMgr.write(RDFDataMgr.java:1014)
        at org.apache.jena.riot.RDFDataMgr.write(RDFDataMgr.java:954)
        at org.aksw.fox.output.AFoxJenaNew.print(AFoxJenaNew.java:113)
        at org.aksw.fox.Fox.getResultsAndClean(Fox.java:91)
        at org.aksw.fox.webservice.FoxServer.fox(FoxServer.java:306)
        at org.aksw.fox.webservice.FoxServer.lambda$mapRoutes$2(FoxServer.java:246)
        at spark.RouteImpl$1.handle(RouteImpl.java:61)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by renespeck** [comment]
It seems that 'graph' is null in 'AFoxJenaNew.java:113' but we never never set it to null.
